configuration:
  swagger:
    app: 'Job Search Platform-User Service'
    description: 'A simple job search platform built with Spring Boot'
    developer: 'Melisa Geca'
    email: 'melisa.geca@stu.ibu.edu.ba'

  mailsender:
    default: 'mailgun'


spring:
  data:
    mongodb:
      uri: mongodb+srv://melisageca:MelisaGeca55@job.oqxsoau.mongodb.net/?retryWrites=true&w=majority
      database: job

email:
  mailgun:
    domain: https://api.mailgun.net/v3/sandboxc84ad8238d2c4c0bbd61784b0c4410c9.mailgun.org
    from-email: Job Search Platform <mailgun@sandbox29278405945b4dc68ec56e4e841715a0.mailgun.org>
    username: api
    password: eed0a9c1d3fd731d4211e870769473fd-69a6bd85-5571a893
security:
  jwt:
    secret: '8qcnHgAnPM8M2fYBFulJWAdtMjQ9K7gREiKwK0ZP4SJbG7lmmT'

