configuration:
  swagger:
    app: 'Job Search Platform'
    description: 'A simple job search platform built with Spring Boot'
    developer: 'Melisa Geca'
    email: 'melisa.geca@stu.ibu.edu.ba'
  mailsender:
    default: 'sendgrid'


spring:
  data:
    mongodb:
      uri: mongodb+srv://melisageca:MelisaGeca55@job.oqxsoau.mongodb.net/?retryWrites=true&w=majority
      database: job

