configuration:
  swagger:
    app: 'Job Search Platform'
    description: 'A simple job search platform built with Spring Boot'
    developer: 'Melisa Geca'
    email: 'melisa.geca@stu.ibu.edu.ba'
  mailsender:
    default: 'sendgrid'


spring:
  data:
    mongodb:
      uri: mongodb+srv://melisageca:MelisaGeca55@job.oqxsoau.mongodb.net/?retryWrites=true&w=majority
      database: job

security:
  jwt:
    secret: '8qcnHgAnPM8M2fYBFulJWAdtMjQ9K7gREiKwK0ZP4SJbG7lmmT'

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
